### PR TITLE
Initial support for impsort engine

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@ctubbsii do you have any time to review this ?

**Comment by ctubbsii** [comment]
> @ctubbsii do you have any time to review this ?

I'm really not familiar with gradle plugins at all, but don't see any obvious issues with this.

**Comment by lburgazzoli** [comment]
I was just feeling guilty to merge it myself

**Review by ctubbsii — APPROVED** [review]

**Comment by ctubbsii** [comment]
> I was just feeling guilty to merge it myself

Haha, no worries. I gave it an "approval" checkmark so you don't have to feel guilty. :smiley_cat:

**Pull request merged**
